#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import subprocess
import sys


def popen(txt):
    proc = subprocess.Popen(
                            txt,
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            shell=True,
                            text=True
                           )
    proc.communicate()
    proc.wait()


popen("python3 setup.py sdist")
popen("python3 -m pip wheel -e .")
popen("mv *.whl dist")
