#!/usr/bin/env python3


"This file is placed in the Public Domain."


import os
import sys


os.environ["PATH"] += ":fin" 


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()


def main():
    popen("rm -fR build dist MANIFEST *.egg-info")
    popen("rm -fR .pytest_cache .test  __pycache__ *~")
    popen('rm -fR html docs/genocide.*.rst')
    popen("loop . rm -fR *~")
    popen("loop . rm -fR __pycache__")


if __name__ == "__main__":
    main()
