#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import subprocess
import sys


os.environ["PATH"] += ":fin" 


def popen(txt):
    proc = subprocess.Popen(
                            txt,
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            shell=True,
                            text=True
                           )
    proc.communicate()
    proc.wait()


def main():
    popen("rm -fR build dist MANIFEST *.egg-info")
    popen("rm -fR .pytest_cache .test  __pycache__ *~")
    popen('rm -fR html docs/genocide.*.rst')
    popen("loop . rm -fR *~")
    popen("loop . rm -fR __pycache__")


if __name__ == "__main__":
    main()
