#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import subprocess
import sys


os.environ["PATH"] += ":fin"


def popen(txt):
    proc = subprocess.Popen(
                            txt.split(),
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            text=True
                           )
    proc.communicate()
    proc.wait()


if not os.path.exists("env"):
    popen("mkenv")


if not os.path.exists("env/bin/sphinx-build"):
    popen("upenv")

#popen("env/bin/python3 -m pip install . --upgrade --force-reinstall --no-cache-dir --no-deps")
popen("env/bin/python3 env/bin/sphinx-build docs html")
