#!/usr/bin/env python3
# This file is placed in the Public Domain.


"documentation"


import os
import sys


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()

if not os.path.exists("env"):
     popen("fin/env")


if not os.path.exists("env/bin/sphinx-build"):
    popen("env/bin/pip3 install -r docs/requirements.txt --upgrade --force-reinstall --no-cache-dir --no-deps")

popen("env/bin/python3 env/bin/sphinx-build docs html")
