#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import subprocess
import sys


SKIP = [
        "env",
       ]


def files(path, txt):
    older = os.getcwd()
    os.chdir(path)
    for fnn in os.listdir(path):
        if fnn.startswith(".") or fnn.startswith("_"):
            continue
        if fnn in SKIP:
            continue
        fpath = os.path.abspath(os.path.join(path, fnn))
        if os.path.isdir(fpath):
            print(fpath)
            files(fpath, txt)
            continue
        if not fnn.endswith(".py"):
            continue
        popen(txt + " " + fpath)
    os.chdir(older)


def popen(txt):
    proc = subprocess.Popen(
                            txt.split(),
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            text=True
                           )
    proc.communicate()
    proc.wait()


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("files <dir> <cmd>")
    else:
        files(sys.argv[1], " ".join(sys.argv[2:]))
