#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


os.environ["PATH"] += ":fin"
os.environ["PYTHONPATH"] = os.getcwd()
os.environ["PYTHONUNBUFFERED"] = "1"


SKIP = ["***", "---", "Your code"]
SKIPDIR = ["docs", "files"]


def doskip(txt):
    if not txt.strip():
        return True
    for skp in SKIP:
        if skp in txt:
            return True
    return False


def loop(path, txt):
    old = os.getcwd()
    os.chdir(path)
    for fnn in os.listdir(path):
        if fnn in SKIPDIR:
            continue
        if fnn.startswith("."):
            continue
        #if not os.path.exists("%s/__init__.py" % fnn):
        #    continue
        old = os.getcwd()
        fpath = os.path.abspath(os.path.join(path, fnn))
        if os.path.isdir(fpath):
            loop(fpath, txt)
        if not os.path.isdir(fpath):
            continue
        os.chdir(fpath)
        for fnm in os.listdir(fpath):
            popen(txt + " " + fnm)
            print(f"{fpath}/{fnm}") 
            sys.stdout.flush()
        os.chdir(old)
    os.chdir(old)


def popen(txt):
    proc = subprocess.Popen(
                            txt.split(),
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            text=True
                           )
    proc.communicate()
    proc.wait()


if __name__ == "__main__":
    popen("wipe")
    loop(os.getcwd(), "pylint -Ev -d E0402")
