#!/usr/bin/env python3
# This file is placed in the Public Domain.


"lint"


import os
import sys


SKIP = ["---", "Your code"]
TODO = ["genocide", "modules"]


def doskip(txt):
    if not txt.rstrip():
        return True
    for skp in SKIP:
        if skp in txt:
            return True
    return False


def loop(path, txt):
    old = os.getcwd()
    os.chdir(path)
    for fnn in os.listdir(path):
        if fnn not in TODO:
            continue
        old = os.getcwd()
        fpath = os.path.abspath(os.path.join(path, fnn))
        if os.path.isdir(fpath):
            loop(fpath, txt)
        if not os.path.isdir(fpath):
            continue
        print(fpath)
        os.chdir(fpath)
        popen(txt)
        os.chdir(old)
        #os.chdir("..")
    os.chdir(old)


def popen(txt):
    for line in os.popen(txt).readlines():
        if doskip(line):
            continue
        print(line.rstrip())
        sys.stdout.flush()


if __name__ == "__main__":
    popen("fin/clean")
    loop(os.getcwd(), "pylint *")
