#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import subprocess
import sys


os.environ["PATH"] += ":fin"


def popen(txt):
    proc = subprocess.Popen(
                            txt.split(),
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            text=True
                           )
    proc.communicate()
    proc.wait()


name = os.getcwd()


if not os.path.exists("dist"):
    popen("build")


popen("python3 -mvirtualenv --system-site-packages env")
popen("env/bin/pip3 install %s -f dist --upgrade --force-reinstall --no-cache-dir --no-deps" % name)
