#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import subprocess
import sys


os.environ["PATH"] += ":fin"


def popen(txt):
    proc = subprocess.Popen(
                            txt.split(),
                            stdin=sys.stdin,
                            stdout=sys.stdout,
                            stderr=sys.stderr,
                            close_fds=False,
                            text=True
                           )
    proc.communicate()
    proc.wait()


popen("clean")
popen("rm -fR env")
