#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


def popen(txt, silent=False):
    for line in os.popen(txt).readlines():
        if silent:
            continue
        print(line.strip())
        sys.stdout.flush()

popen("rm -fR docs/genocide.*.rst")
popen("rm -fR html")