#!/usr/bin/env python3
# This file is placed in the Public Domain.


"check"


import os


allmod = [
       "__import__",
       "__main__",
       "__version__",
       '"## "',
       "popen",
       "pkgutil",
       "importlib",
       "print",
       "sys",
       "traceback"
      ]

skip = [
        "env",
        "bin",
        "dev",
        "test",
        ".git",
        "README",
        "grep",
        "mod"
       ]

targets = ["genocide",]

TXT  = "grep -R %s %s"


def doskip(txt):
    for name in skip:
        if name in txt:
            return True
    return False


def main():
    for target in targets:
        for txt in allmod:
            greptxt = TXT % (txt, target)
            for line in os.popen(greptxt).readlines():
                if doskip(line):
                    continue
                print(line.rstrip())


main()
