#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import shutil


mods = ["csl", "evt", "hdl", "obj", "rpt",  "rss", "tme", "thr", "usr"]


def popen(txt):
    for l in os.popen(txt).readlines():
        print(l)


popen("rm -fR txt/*~ files/*~ files/__pycache__")
popen("rm -fR bin/*~ *~ __pycache__")
popen("rm -fR build dist MANIFEST genocide.egg-info") 
popen("rm -fR dev/*~ bin/*~ *~ files/*~")
popen("rm -fR lib/*~ lib/__pycache__ lib/genocide.egg-info")
popen("rm -fR genocide/*~ genocide/__pycache__")
popen("rm -fR genocide/cmd/*~ genocide/cmd/__pycache__")
popen("rm -fR .test test/__pycache__ test/*~")
popen("rm -fR html tar")

for mn in mods:
    try:
        os.unlink(os.path.join("docs", "%s.rst" % mn))
    except:
        pass

popen("rm -fR docs/*~ docs/_static/*~ docs/_templates/*~")
popen("rm -fR docs/bot*.rst docs/mod*.rst")
popen("rm -fR html")
popen("rm -fR docs/*~ docs/_static/*~ docs/_templates/*~")
popen("rm -fR docs/genocide.*.rst")
