#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import shutil


mods = ["obb", "obe", "obh", "obj", "obr", "obt", "obu"]


def popen(txt):
    for l in os.popen(txt).readlines():
        print(l)

for m in mods:
    fn = "docs/%s.rst" % m
    if os.path.exists(fn):
        popen("rm " + fn)

popen("rm -fR txt/*~ files/*~ files/__pycache__")
popen("rm -fR bin/*~ *~ __pycache__")
popen("rm -fR build dist MANIFEST genocide.egg-info") 
popen("rm -fR dev/*~ bin/*~ *~ files/*~")
popen("rm -fR lib/*~ lib/__pycache__ lib/genocide.egg-info")
popen("rm -fR lib2/*~ lib2/__pycache__ lib2/genocide.egg-info")
popen("rm -fR genocide/*~ genocide/__pycache__")
popen("rm -fR genocide/cmd/*~ genocide/cmd/__pycache__")
popen("rm -fR .test test/__pycache__ test/*~")
popen("rm -fR html tar")
popen("rm -fR docs/*~ docs/_static/*~ docs/_templates/*~")
popen("rm -fR docs/bot*.rst docs/mod*.rst")
popen("rm -fR html")
popen("rm -fR docs/*~ docs/_static/*~ docs/_templates/*~")
popen("rm -fR docs/genocide.*.rst")
popen("rm -fR mod/*~ mod/__pycache__")
