#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


sys.path.insert(0, os.getcwd())

os.environ["PYTHONPATH"] = "."

txt = "E1121,E1101,E0102,R0801,R0001,C0413,C0412,C0414,C0201,C0209,C0415,C0301,C0413,W1505,W0603,W0622,W0212,W0703,W0613,R0915,R0912,R1732,R1710,R0201,R0903,R0902,C0411,C0116,C0114,C0115,C0103"


def popen(txt):
    for line in os.popen(txt).readlines():
        l = line.strip()
        if "Your code" in l:
            continue
        if ":" in l:
            yield line.replace("\n", "")          


def main():
    for fn in os.listdir("genocide"):
        if "__" in fn or fn.endswith("~"):
            continue
        mn = fn.split(os.sep)[-1]
        for line in popen("pylint -d %s genocide/%s" % (txt, mn)):
            print(line)
    for fn in os.listdir("test"):
        if "__" in fn or fn.endswith("~"):
            continue
        mn = fn.split(os.sep)[-1]
        for line in popen("pylint -d %s test/%s" % (txt, mn)):
            print(line)


main()
