#!/usr/bin/env python3
# This file is placed in the Public Domain.


import importlib
import os
import sys


wd =  os.getcwd()
print(wd)
sys.path.insert(0, wd)
sys.path.insert(0, os.path.join(wd, "lib"))


mns = ["genocide"]

mods = [
        "genocide.csl",
        "genocide.evt",
        "genocide.hdl",
        "genocide.irc",
        "genocide.mbx",
        "genocide.mdl",
        "genocide.obj",
        "genocide.rss",
        "genocide.scn",
        "genocide.thr",
        "genocide.tbl",
        "genocide.tme",
        "genocide.thr",
        "genocide.udp",
        "genocide.usr",
        "genocide.cmd.bsc",
        "genocide.cmd.irc",
        "genocide.cmd.mbx",
        "genocide.cmd.mdl",
        "genocide.cmd.req",
        "genocide.cmd.rss",
        "genocide.cmd.slg",
        "genocide.cmd.trt",
       ]

txt = "E1121,E1101,E0102,R0801,R0001,C0413,C0412,C0414,C0201,C0209,C0415,C0301,C0413,W1505,W0603,W0622,W0611,W0212,W0703,W0613,R0915,R0912,R1732,R1710,R0201,R0903,R0902,C0411,C0116,C0114,C0115,C0103"


def popen(txt):
    for line in os.popen(txt).readlines():
        l = line.strip()
        if "Your code" in l:
            yield line.replace("\n", "")
        if ":" in l:
            yield line.replace("\n", "")          


import genocide


import genocide.cmd.all


def main():
    for mn in mods:
        importlib.import_module(mn)
    for mn in mns:
        for line in popen("pylint --extension-pkg-whitelist=mdl -d %s %s" % (txt, mn)):
            print(line)

main()
