#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


def main():
    if len(sys.argv) != 2:
        print("rep <fn>")
        os._exit(0)
    for line in open(sys.argv[1], "r").readlines():
         print(line.strip())


main()