#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import inspect
import os
import queue
import shutil
import sys
import unittest


sys.path.insert(0, os.getcwd())


import op.obj
op.obj.workdir = ".test"


from op.run import Config


Config.debug = True
Config.verbose = False
Config.version = 72
Config.workdir = ".test"


from op.run import Config, Table, dispatch
from op.evt import Command
from op.hdl import Callbacks, Handler


from genocide import bsc, fnd, irc, log, mdl, rss, sts, tdo


Table.add(bsc)
Table.add(fnd)
Table.add(irc)
Table.add(log)
Table.add(mdl)
Table.add(rss)
Table.add(sts)
Table.add(tdo)


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS


class CLI(Handler):

     def raw(self, txt):
         if Config.verbose:
             print(txt)
        
         
c = CLI()
c.start()


def main():
    if os.path.exists(Config.workdir):
        shutil.rmtree(Config.workdir)
    if "-v" in sys.argv:
        print("Verbose")
        Config.verbose = True
    Table.scan()
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)


main()
