#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import inspect
import os
import queue
import shutil
import sys
import unittest


sys.path.insert(0, os.getcwd())
sys.path.insert(0, "lib")


from genocide.obj import Config, format


Config.debug = True
Config.verbose = False
Config.workdir = ".test"


from genocide.evt import Command
from genocide.hdl import Callbacks, Handler, dispatch


Callbacks.threaded = False


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS


class CLI(Handler):

     def raw(self, txt):
         if Config.verbose:
             print(txt)
        
         
Callbacks.add("command", dispatch)


c = CLI()
c.start()


def main():
    if os.path.exists(Config.workdir):
        shutil.rmtree(Config.workdir)
    if "-v" in sys.argv:
        Config.verbose = True
    print(format(Config))
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)


main()
