#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import inspect
import os
import shutil
import sys
import unittest


sys.path.insert(0, os.getcwd())


from gcd.obj import Config, format, values
from gcd.prs import parse


import gcd.cmds


Config.debug = True
Config.workdir = ".test"


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS


def main():
    if os.path.exists(Config.workdir):
        shutil.rmtree(Config.workdir)
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)

main()
